### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [BlakeJohnson117/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
> This is a good start, but we'd like to see another sub-layer to know that you're able to continue breaking down steps. 
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The three methods I chose for **Class #1** represent behaviors or actions.
> `Fire_Employee` and `Promote_Employee` are good methods for the `employee` class, although you might want to consider naming them just `fire` and `promote` since you're already calling the methods on an employee (for example: `blake.promote` and `blake.fire` look/sound better than `blake.promote_employee` and `blake.fire_employee`)
> For the `Add_Employee` method, this sounds like a method more suited to a `Team`  or `Organization` or `Business` class. Otherwise, it sounds like you're adding an employee to an employee which doesn't make a lot of sense. 
- [x] I described what the methods do in **Class 1**.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The three methods I chose for **Class #2** represent behaviors or actions.
> Similar feedback for this class. `Update_Price` and `Remove_Nuts` are perfect methods for a `Food` class. The method `Add_Food` probably belongs on a `Menu` class instead; otherwise, you're adding a food to a food. 
- [x] I described what the methods do in **Class 2**.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [x] Technical Ready
- [ ] Pending
> Next steps: 
> 1) Add one more layer of sub-steps to your top down design file. 
> 2) Create one more file called `class_3.txt` and define a class that you would find in a city. Be sure that the methods are all actions of/for that specific class. Create another file called `class_3_example_object.txt` and give the attributes and methods for a specific object of that class.
- [ ] Not Technical Ready

**Comment by BlakeJohnson117** [comment]
https://github.com/BlakeJohnson117/mod_0_skills

Please see my updated repo!

-Blake Johnson

**Comment by rwarbelow** [comment]
Looks good! 👍
